AppBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: text
        fullname:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
