AppBundle\Entity\Users:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\UsersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '255'
        password:
            type: string
            length: '255'
        email:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
