<?php

namespace AppBundle\Entity;

/**
 * MarksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarksRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByIds()
	{
		return $this->getEntityManager()
        			->createQuery('SELECT m.id FROM AppBundle:Marks m')
            		->getResult();
	}
}
