<?php

namespace AppBundle\Entity;

/**
 * ModelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelsRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllIDs($markID)
	{
		return $this->getEntityManager()
        			->createQuery('SELECT m.id, m.modelsName FROM AppBundle:Models m WHERE m.markId = :id')
        			->setParameter('id', $markID)
            		->getResult();
	}
}
